import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";

export default function Model(props) {
  const { nodes, materials } = useGLTF(require("../assets/model.glb"));
  return (
    <group {...props} dispose={null} scale={1} position={[0, -1, 0]}>
      <group scale={0.01}>
        <group
          position={[96.208, 37.613, 130.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engbaycrap_etk_engine_i6_0.geometry}
            material={materials.etk_engine_i6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engbaycrap_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engbaycrap_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engbaycrap_amdb11_bolt_0.geometry}
            material={materials.amdb11_bolt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engbaycrap_amdb11_stickers_0.geometry}
            material={materials.amdb11_stickers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engbaycrap_amdb11_leather_3_0.geometry}
            material={materials.amdb11_leather_3}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v8_amdb11_leather_3_0.geometry}
            material={materials.amdb11_leather_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v8_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v8_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v8_amdb11_engine_0.geometry}
            material={materials.amdb11_engine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v8_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_intake_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_intake_amdb11_bolt_0.geometry}
            material={materials.amdb11_bolt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_intake_amdb11_leather_3_0.geometry}
            material={materials.amdb11_leather_3}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_radiator_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_radiator_amdb11_engine_0.geometry}
            material={materials.amdb11_engine}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_strutbrace_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_strutbrace_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_strutbrace_amdb11_bolt_0.geometry}
            material={materials.amdb11_bolt}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_engine_0.geometry}
            material={materials.amdb11_engine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_bolt_0.geometry}
            material={materials.amdb11_bolt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_stickers_0.geometry}
            material={materials.amdb11_stickers}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_engine_v12_amdb11_leather_3_0.geometry}
            material={materials.amdb11_leather_3}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_R_amdb11_stitch_1_0.geometry}
            material={materials.amdb11_stitch_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_R_amdb11_stitch_2_0.geometry}
            material={materials.amdb11_stitch_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_R_amdb11_trim_0.geometry}
            material={materials.amdb11_trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_R_amdb11_leather_2_0.geometry}
            material={materials.amdb11_leather_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_R_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_R_amdb11_finish_0.geometry}
            material={materials.amdb11_finish}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_L_amdb11_stitch_1_0.geometry}
            material={materials.amdb11_stitch_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_L_amdb11_stitch_2_0.geometry}
            material={materials.amdb11_stitch_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_L_amdb11_trim_0.geometry}
            material={materials.amdb11_trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_L_amdb11_leather_2_0.geometry}
            material={materials.amdb11_leather_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_L_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_doorpanel_L_amdb11_finish_0.geometry}
            material={materials.amdb11_finish}
          />
        </group>
        <group
          position={[50.955, 60.406, 53.849]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakepedal_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakepedal_amdb11_interior_0.geometry}
            material={materials.amdb11_interior}
          />
        </group>
        <group
          position={[31.389, 30.083, 40.554]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_gaspedal_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_gaspedal_amdb11_interior_0.geometry}
            material={materials.amdb11_interior}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_stitch_2_0.geometry}
            material={materials.amdb11_stitch_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_detail_2_0.geometry}
            material={materials.amdb11_detail_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_leather_0.geometry}
            material={materials.amdb11_leather}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_leather_2_0.geometry}
            material={materials.amdb11_leather_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FR_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_stitch_2_0.geometry}
            material={materials.amdb11_stitch_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_detail_2_0.geometry}
            material={materials.amdb11_detail_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_leather_0.geometry}
            material={materials.amdb11_leather}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_seat_FL_amdb11_leather_2_0.geometry}
            material={materials.amdb11_leather_2}
          />
        </group>
        <group
          position={[40.399, 84.119, 3.738]}
          rotation={[-2.875, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_interior_0.geometry}
            material={materials.amdb11_interior}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_symbols2_0.geometry}
            material={materials.amdb11_symbols2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_badging_chrome_0.geometry}
            material={materials.amdb11_badging_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_leather_0.geometry}
            material={materials.amdb11_leather}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_interior_light_0.geometry}
            material={materials.amdb11_interior_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_leather_3_0.geometry}
            material={materials.amdb11_leather_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_steer_amdb11_finish_0.geometry}
            material={materials.amdb11_finish}
          />
        </group>
        <group
          position={[86.624, 37.576, 130.16]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR_amdb11_caliper_0.geometry}
            material={materials.amdb11_caliper}
          />
        </group>
        <group
          position={[86.624, 37.576, 130.16]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR_amdb11_brake_0.geometry}
            material={materials.amdb11_brake}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
        </group>
        <group
          position={[47.047, 84.287, 8.871]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_signalstalk_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_signalstalk_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_signalstalk_amdb11_interior_light_0.geometry}
            material={materials.amdb11_interior_light}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_L_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_L_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_L_amdb11_black_2_0.geometry}
            material={materials.amdb11_black_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_L_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_L_amdb11_mirrors_0.geometry}
            material={materials.amdb11_mirrors}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_L_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_L_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_L_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_L_amdb11_black_2_0.geometry}
            material={materials.amdb11_black_2}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_runninglight_0.geometry}
            material={materials.amdb11_runninglight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_signal_R_0.geometry}
            material={materials.amdb11_signal_R}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_highbeam_0.geometry}
            material={materials.amdb11_highbeam}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_headlight_0.geometry}
            material={materials.amdb11_headlight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_R_amdb11_headlights_0.geometry}
            material={materials.amdb11_headlights}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_runninglight_0.geometry}
            material={materials.amdb11_runninglight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_signal_L_0.geometry}
            material={materials.amdb11_signal_L}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_headlight_0.geometry}
            material={materials.amdb11_headlight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_highbeam_0.geometry}
            material={materials.amdb11_highbeam}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_headlight_L_amdb11_headlights_0.geometry}
            material={materials.amdb11_headlights}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_R_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_R_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_R_amdb11_black_2_0.geometry}
            material={materials.amdb11_black_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_R_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_mirror_R_amdb11_mirrors_0.geometry}
            material={materials.amdb11_mirrors}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_R_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_R_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_R_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_door_R_amdb11_black_2_0.geometry}
            material={materials.amdb11_black_2}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_L_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_L_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_L_amdb11_taillight_0.geometry}
            material={materials.amdb11_taillight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_L_amdb11_signal_RL_0.geometry}
            material={materials.amdb11_signal_RL}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_L_amdb11_rearglass_0.geometry}
            material={materials.amdb11_rearglass}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_R_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_R_amdb11_taillight_0.geometry}
            material={materials.amdb11_taillight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_R_amdb11_signal_RR_0.geometry}
            material={materials.amdb11_signal_RR}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_taillight_R_amdb11_rearglass_0.geometry}
            material={materials.amdb11_rearglass}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_R_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_R_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_R_amdb11_taillight_0.geometry}
            material={materials.amdb11_taillight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_R_amdb11_signal_RL_0.geometry}
            material={materials.amdb11_signal_RL}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_R_amdb11_rearglass_0.geometry}
            material={materials.amdb11_rearglass}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_L_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_L_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_L_amdb11_taillight_0.geometry}
            material={materials.amdb11_taillight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_L_amdb11_signal_RL_0.geometry}
            material={materials.amdb11_signal_RL}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunklight_L_amdb11_rearglass_0.geometry}
            material={materials.amdb11_rearglass}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunk_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunk_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunk_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunk_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunk_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_trunk_amdb11_badging_chrome_0.geometry}
            material={materials.amdb11_badging_chrome}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_exhtips_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_exhtips_amdb11_silver_0.geometry}
            material={materials.amdb11_silver}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_glass_0.geometry}
            material={materials.amdb11_glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_reverselight_0.geometry}
            material={materials.amdb11_reverselight}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_R_amdb11_amr_0.geometry}
            material={materials.amdb11_amr}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_hood_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_hood_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_hood_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_hood_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_hood_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_hood_amdb11_badging_chrome_0.geometry}
            material={materials.amdb11_badging_chrome}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_badging_chrome_0.geometry}
            material={materials.amdb11_badging_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_grille_0.geometry}
            material={materials.amdb11_grille}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_black_2_0.geometry}
            material={materials.amdb11_black_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_bumper_F_amdb11_amr_0.geometry}
            material={materials.amdb11_amr}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_lights_0.geometry}
            material={materials.amdb11_lights}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_0.geometry}
            material={materials.amdb11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_grey_0.geometry}
            material={materials.amdb11_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_glass_0.geometry}
            material={materials.amdb11_glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_badging_chrome_0.geometry}
            material={materials.amdb11_badging_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_stitch_2_0.geometry}
            material={materials.amdb11_stitch_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_interior_0.geometry}
            material={materials.amdb11_interior}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_detail_0.geometry}
            material={materials.amdb11_detail}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_detail_2_0.geometry}
            material={materials.amdb11_detail_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_trim_0.geometry}
            material={materials.amdb11_trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_leather_0.geometry}
            material={materials.amdb11_leather}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_black_2_0.geometry}
            material={materials.amdb11_black_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_roof_0.geometry}
            material={materials.amdb11_roof}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_grille_0.geometry}
            material={materials.amdb11_grille}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_leather_2_0.geometry}
            material={materials.amdb11_leather_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_leather_3_0.geometry}
            material={materials.amdb11_leather_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_chmsl_0.geometry}
            material={materials.amdb11_chmsl}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_gauge_0.geometry}
            material={materials.amdb11_gauge}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_screen_2_0.geometry}
            material={materials.amdb11_screen_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_interior_light_0.geometry}
            material={materials.amdb11_interior_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_amr_0.geometry}
            material={materials.amdb11_amr}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_gauge_speedo_0.geometry}
            material={materials.amdb11_gauge_speedo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_wheel_grey_0.geometry}
            material={materials.amdb11_wheel_grey}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_body_amdb11_finish_0.geometry}
            material={materials.amdb11_finish}
          />
        </group>
        <group
          position={[-96.675, 37.613, 130.16]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03001_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03001_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
        </group>
        <group
          position={[-87.091, 37.576, 130.151]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR001_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR001_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR001_amdb11_caliper_0.geometry}
            material={materials.amdb11_caliper}
          />
        </group>
        <group
          position={[-87.091, 37.576, 130.151]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_brake_0.geometry}
            material={materials.amdb11_brake}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.amdb11_brakedisc_FR001_amdb11_misc_chrome_0.geometry
            }
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR001_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
        </group>
        <group
          position={[96.208, 37.613, -161.727]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03002_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03002_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
        </group>
        <group
          position={[86.624, 37.576, -161.719]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR002_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR002_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR002_amdb11_caliper_0.geometry}
            material={materials.amdb11_caliper}
          />
        </group>
        <group
          position={[86.624, 37.576, -161.719]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_brake_0.geometry}
            material={materials.amdb11_brake}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.amdb11_brakedisc_FR002_amdb11_misc_chrome_0.geometry
            }
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR002_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
        </group>
        <group
          position={[-96.675, 37.613, -161.719]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03003_amdb11_mirror_0.geometry}
            material={materials.amdb11_mirror}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_wheel_03003_amdb11_black_ext_0.geometry}
            material={materials.amdb11_black_ext}
          />
        </group>
        <group
          position={[-87.091, 37.576, -161.727]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR003_amdb11_misc_chrome_0.geometry}
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR003_amdb11_badging_0.geometry}
            material={materials.amdb11_badging}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_caliper_FR003_amdb11_caliper_0.geometry}
            material={materials.amdb11_caliper}
          />
        </group>
        <group
          position={[-87.091, 37.576, -161.727]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_brake_0.geometry}
            material={materials.amdb11_brake}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.amdb11_brakedisc_FR003_amdb11_misc_chrome_0.geometry
            }
            material={materials.amdb11_misc_chrome}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.amdb11_brakedisc_FR003_amdb11_misc_0.geometry}
            material={materials.amdb11_misc}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_intake_v8_amdb11_leather_3_0.geometry}
          material={materials.amdb11_leather_3}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_bumperbar_F_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_tierod_F_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_swaybar_F_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_subframe_F_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_strut_F_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_steeringbox_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_lowerarm_F_b_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_lowerarm_F_a_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_hub_F_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_upperarm_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_tierod_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_swaybar_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_subframe_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_spring_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_shock_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_lowerarm_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_hub_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_halfshaft_R_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_diff_etkc_0.geometry}
          material={materials.etkc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_brakedisc_RR_amdb11_brake_0.geometry}
          material={materials.amdb11_brake}
          position={[86.624, 37.576, 128.985]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_headlightglass_R_amdb11_glass_0.geometry}
          material={materials.amdb11_glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_headlightglass_L_amdb11_glass_0.geometry}
          material={materials.amdb11_glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_doorglass_R_amdb11_glass_0.geometry}
          material={materials.amdb11_glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_sideglass_R_amdb11_glass_tint_0.geometry}
          material={materials.amdb11_glass_tint}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_backlight_amdb11_glass_tint_0.geometry}
          material={materials.amdb11_glass_tint}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_sideglass_L_amdb11_glass_tint_0.geometry}
          material={materials.amdb11_glass_tint}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_doorglass_L_amdb11_glass_0.geometry}
          material={materials.amdb11_glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.amdb11_windshield_amdb11_glass_0.geometry}
          material={materials.amdb11_glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object_4003_Scene_-_Root_0"].geometry}
          material={materials["Scene_-_Root"]}
          position={[84.44, 37.613, 130.151]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object_4001_Scene_-_Root_0"].geometry}
          material={materials["Scene_-_Root"]}
          position={[-84.907, 37.613, 130.16]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object_4002_Scene_-_Root_0"].geometry}
          material={materials["Scene_-_Root"]}
          position={[84.44, 37.613, -161.727]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object_4004_Scene_-_Root_0"].geometry}
          material={materials["Scene_-_Root"]}
          position={[-84.907, 37.613, -161.719]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(require("../assets/model.glb"));
